# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
test:
  adapter: postgresql
#  username: postgres
  database: libraryApp_test
#  password: root
  host: localhost

development:
  adapter: postgresql
#  username: postgres
  database: libraryApp_dev
#  password: root
  host: localhost
